# ----------------------------------------------------------------------------
#
# Package             : allennlp
# Source Repo         : https://github.com/allenai/allennlp
# Travis Job Link     : https://travis-ci.com/github/asellappen/allennlp/
# Created travis.yml  : Yes
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
language: python

disct: bionic
arch:

    - ppc64le
    
python:
    - 3.7  
    - 3.8
    
before_install:
   #pytorch not supproted for ppc64le
   - if [ "$TRAVIS_CPU_ARCH" = "ppc64le" ]; then
        sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran;
        pip install torch==1.7.0+cu110 torchvision==0.8.1+cu110 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html;
     fi
     
install:
    - make install
    - make format

script:	
    - make lint
    - make typecheck
    - make test-with-cov
