# ----------------------------------------------------------------------------
#
# Package             : allennlp
# Source Repo         : https://github.com/allenai/allennlp
# Travis Job Link     : https://travis-ci.com/github/asellappen/allennlp/
# Created travis.yml  : Yes
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
language: python

disct: bionic
arch:
    - ppc64le
    
python:
    - 3.7  
before_install:
   #pytorch not supported for ppc64le
   - if [ "$TRAVIS_CPU_ARCH" = "ppc64le" ]; then
        grep -iv  "torch" Makefile>/tmp/Makefiletmp;
        grep -iv nltk /tmp/Makefiletmp>Makefile;
     fi
     
install:
    - cat Makefile
    - make install
    - make format

script:	
    - make lint
    - make typecheck
    - make test-with-cov
